services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: food_world
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: food123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ../../backend/Online-food
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: food123
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../../frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql-data:
