sonar.projectKey=food-app

sonar.projectName=food-app

sonar.sources=src

sonar.java.binaries=target/classes

sonar.host.url=http://3.109.133.235:9000

sonar.login=sqa_b11add870d2082359ad220796f9c2d8f1a990b8b

