apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: food-app

spec:

  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: whoistimothyshandy/food-backend:latest

        ports:

        - containerPort: 8080

        env:

        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: food-config
              key: MYSQL_HOST

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
